#!/usr/bin/env bash

# Check which waybar theme is set
CURRENT_STYLE=$(readlink -f ~/.config/waybar/style.css 2>/dev/null || echo "")
CURRENT_BASENAME=$(basename "$CURRENT_STYLE")

# ------------------------------------ VARIABLES
if [[ "$CURRENT_BASENAME" == *"-dark.css"  ]]; then
    SWITCHTO=""
    THEMENAME="rose-pine-dawn"
else
    SWITCHTO="-dark"
    THEMENAME="rose-pine"
fi

# ------------------------------------ WAYBAR
ln -sf ~/.config/waybar/style/style$SWITCHTO.css ~/.config/waybar/style.css

# ------------------------------------ BACKGROUND
BG_PATH="$HOME/.config/hypr/wallpapers/wallpaper.jpg"
ln -sf ~/.config/hypr/wallpapers/themes/images$SWITCHTO/link "$BG_PATH"

# Show new wallpaper immediately
swww img "$BG_PATH" --transition-type any --transition-duration 1.5 &

# Generate rofi / wlogout versions in the background
(
  magick "$BG_PATH" -resize 1920x1200\> -quality 100 ~/.config/rofi/wallpaper.jpg
  cp ~/.config/rofi/wallpaper.jpg ~/.config/wlogout/wallpaper.jpg
  magick ~/.config/wlogout/wallpaper.jpg -blur 0x8 ~/.config/wlogout/wallpaper.jpg
) &

if [ "$SWITCHTO" = "-dark" ]; then
	# copy config files gtk4
    # ln -sf ~/.themes/Catppuccin-BL-LB-Dark/gtk-4.0/gtk-dark.css ~/.config/gtk-4.0
    # ln -sf ~/.themes/Catppuccin-BL-LB-Dark/gtk-4.0/gtk.css ~/.config/gtk-4.0
    # ln -sf ~/.themes/Catppuccin-BL-LB-Dark/gtk-4.0/assets/ ~/.config/gtk-4.0
    # gsettings set org.gnome.desktop.interface gtk-theme 'Catppuccin-BL-LB-Dark'

	gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3-dark'
    gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
    gsettings set org.gnome.desktop.interface icon-theme "Reversal-dark"
else
 # copy config files gtk4
    # ln -sf ~/.themes/Catppuccin-BL-LB-Light/gtk-4.0/gtk-dark.css ~/.config/gtk-4.0
    # ln -sf ~/.themes/Catppuccin-BL-LB-Light/gtk-4.0/gtk.css ~/.config/gtk-4.0
    # ln -sf ~/.themes/Catppuccin-BL-LB-Light/gtk-4.0/assets/ ~/.config/gtk-4.0
    # gsettings set org.gnome.desktop.interface gtk-theme 'Catppuccin-BL-LB-Light'

	gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3'
    gsettings set org.gnome.desktop.interface color-scheme "prefer-light"
    gsettings set org.gnome.desktop.interface icon-theme "Reversal"
fi

# ------------------------------------ ROFI
ln -sf ~/.config/rofi/style/style$SWITCHTO.rasi ~/.config/rofi/style.rasi

# ------------------------------------ KITTY
ln -sf ~/.config/kitty/style/$KITTYTHEME.conf ~/.config/kitty/style.conf

# ------------------------------------ SWAYNC
ln -sf ~/.config/swaync/style/style$SWITCHTO.css ~/.config/swaync/style.css
# ------------------------------------ SWAYNC RELOAD
pkill -SIGUSR2 swaync
# pkill -SIGUSR2 nautilus

# ------------------------------------ HYPRLOCK
ln -sf ~/.config/hypr/hyprlock/hyprlock$SWITCHTO.conf ~/.config/hypr/hyprlock.conf

# spicetify apply

# ------------------------------------ RESTART WAYBAR
# killall -SIGUSR2 waybar
