#!/usr/bin/env bash

# Check which waybar theme is set
CURRENT_STYLE=$(readlink -f ~/.config/waybar/style.css 2>/dev/null || echo "")
CURRENT_BASENAME=$(basename "$CURRENT_STYLE")

# ------------------------------------ VARIABLES
if [[ "$CURRENT_BASENAME" == *"-dark.css"  ]]; then
    SWITCHTO=""
    THEMENAME="fleet-dark"
else
    SWITCHTO="-dark"
    THEMENAME="fleet-light"
fi

# ------------------------------------ WAYBAR
ln -sf ~/.config/waybar/style/style$SWITCHTO.css ~/.config/waybar/style.css

# ------------------------------------ BACKGROUND
BG_PATH="$HOME/.config/hypr/wallpapers/wallpaper.jpg"
ln -sf "$HOME/.config/hypr/wallpapers/themes/images$SWITCHTO/link" "$BG_PATH"

pgrep -x awww-daemon >/dev/null || awww-daemon &
sleep 0.2
awww img --transition-type grow --transition-duration 1 "$BG_PATH" &
# Generate rofi / wlogout versions in the background
(
  magick "$BG_PATH" -resize 1920x1200\> -quality 100 ~/.config/rofi/wallpaper.jpg
  cp ~/.config/rofi/wallpaper.jpg ~/.config/wlogout/wallpaper.jpg
  magick ~/.config/wlogout/wallpaper.jpg -blur 0x8 ~/.config/wlogout/wallpaper.jpg
) &

if [ "$SWITCHTO" = "-dark" ]; then

# GTK
    gsettings set org.gnome.desktop.interface icon-theme "Neuwaita"
	gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3-dark'
    gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"

# QUICKSHELL
	ln -sf ~/.config/quickshell/Commons/ThemeDark.qml ~/.config/quickshell/Commons/Theme.qml

	ln -sf ~/.config/hypr/theme/dark.conf ~/.config/hypr/hyprland/theme.conf

else

# GTK
    gsettings set org.gnome.desktop.interface icon-theme "Neuwaita"
	gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3'
    gsettings set org.gnome.desktop.interface color-scheme "prefer-light"

# QUICKSHELL
	ln -sf ~/.config/quickshell/Commons/ThemeLight.qml ~/.config/quickshell/Commons/Theme.qml

	ln -sf ~/.config/hypr/theme/light.conf ~/.config/hypr/hyprland/theme.conf

fi

# ------------------------------------ ROFI
ln -sf ~/.config/rofi/style/style$SWITCHTO.rasi ~/.config/rofi/style.rasi

# ------------------------------------ SWAYNC
ln -sf ~/.config/swaync/style/style$SWITCHTO.css ~/.config/swaync/style.css

# ------------------------------------ SWAYNC RELOAD
pkill -SIGUSR2 swaync

# ------------------------------------ HYPRLOCK
ln -sf ~/.config/hypr/hyprlock/hyprlock$SWITCHTO.conf ~/.config/hypr/hyprlock.conf



# ------------------------------------ RESTART WAYBAR
# killall -SIGUSR2 waybar
