general {
    lock_cmd = pidof hyprlock || hyprlock
    #before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 600
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}

listener {
    timeout = 150 # 2 mins
    on-timeout = brightnessctl -sd rgb:kbd_backlight set 0
    on-resume = brightnessctl -rd rgb:kbd_backlight
}

# Screen Off
listener {
    timeout = 600   #10 min
    on-timeout = sh -c 'if [ "$(playerctl status 2>/dev/null)" != "Playing" ]; then hyprctl dispatch dpms off; fi'
    on-resume = hyprctl dispatch dpms on && brightnessctl -r
}

# Lock
listener {
    timeout = 900                                    # 8min
    on-timeout = sh -c 'if [ "$(playerctl status 2>/dev/null)" != "Playing" ]; then hyprlock; fi'
}

# Suspend
listener {
    timeout = 1800                                # 30mins
    # on-timeout = systemctl suspend                # suspend pc
    on-timeout = sh -c 'if [ "$(playerctl status 2>/dev/null)" != "Playing" ]; then systemctl suspend; fi'
}
