#!/bin/sh

# Check which waybar theme is set
THEMEIS=$(readlink -f ~/.config/waybar/style.css | cut -d '-' -f2)

# ------------------------------------ VARIABLES
if [ $THEMEIS != "dark.css" ]; then
    SWITCHTO="-dark"
    KITTYTHEME="mocha"
else
    SWITCHTO=""
    KITTYTHEME="latte"
fi

# ------------------------------------ WAYBAR
ln -sf ~/.config/waybar/style/style$SWITCHTO.css ~/.config/waybar/style.css



# ------------------------------------ BACKGROUND
#BG_PATH="$HOME/.config/hypr/wallpapers/wallpaper.jpg"
#ln -sf ~/.config/hypr/wallpapers/themes/images$SWITCHTO/link "$BG_PATH"
#magick ~/.config/hypr/wallpapers/wallpaper.jpg -resize 2300x1294\> -quality 85 ~/.config/rofi/wallpaper.jpg
#cp ~/.config/rofi/wallpaper.jpg ~/.config/wlogout/wallpaper.jpg
#magick ~/.config/wlogout/wallpaper.jpg -blur 0x8 ~/.config/wlogout/wallpaper.jpg
#swww img "$BG_PATH" --transition-type any --transition-duration 2

##update the sddm image


# ------------------------------------ BACKGROUND
BG_PATH="$HOME/.config/hypr/wallpapers/wallpaper.jpg"
ln -sf ~/.config/hypr/wallpapers/themes/images$SWITCHTO/link "$BG_PATH"

# Show new wallpaper immediately
swww img "$BG_PATH" --transition-type any --transition-duration 2 &

# Generate rofi / wlogout versions in the background
(
  magick "$BG_PATH" -resize 2300x1294\> -quality 85 ~/.config/rofi/wallpaper.jpg
  cp ~/.config/rofi/wallpaper.jpg ~/.config/wlogout/wallpaper.jpg
  magick ~/.config/wlogout/wallpaper.jpg -blur 0x8 ~/.config/wlogout/wallpaper.jpg
  ln -sf /usr/share/sddm/themes/sdt/Backgrounds/wallpaper$SWITCHTO.jpg /usr/share/sddm/themes/sdt/wallpaper.jpg
) &




# ------------------------------------ GTK
gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita'
if [ "$SWITCHTO" = "-dark" ]; then

    gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
    gsettings set org.gnome.desktop.interface icon-theme "Adwaita"
else
    gsettings set org.gnome.desktop.interface color-scheme "default"
    gsettings set org.gnome.desktop.interface icon-theme "Adwaita"
fi

# ------------------------------------ GHOSTTY
ln -sf ~/.config/ghostty/themes/$KITTYTHEME.conf ~/.config/ghostty/themes/style.conf

#------------------------------------- GHOSTY RELOAD
if pgrep -x ghostty &> /dev/null; then
  ghostty_addresses=$(hyprctl clients -j | jq -r '.[] | select(.class == "com.mitchellh.ghostty") | .address')

  if [[ -n "$ghostty_addresses" ]]; then
    # Save current active window
    current_window=$(hyprctl activewindow -j | jq -r '.address')

    # Focus each ghostty window and send reload key combo
    while IFS= read -r address; do
      hyprctl dispatch focuswindow "address:$address"
      sleep 0.03
      hyprctl dispatch sendshortcut "CTRL SHIFT, comma, address:$address"
    done <<< "$ghostty_addresses"

    # Return focus to original window
    if [[ -n "$current_window" ]]; then
      hyprctl dispatch focuswindow "address:$current_window"
    fi
  fi
fi

# ------------------------------------ FASTFETCH
ln -sf ~/.config/fastfetch/style/style$SWITCHTO.jsonc ~/.config/fastfetch/config.jsonc

# ------------------------------------ ROFI
ln -sf ~/.config/rofi/style/style$SWITCHTO.rasi ~/.config/rofi/style.rasi

# ------------------------------------ KITTY
ln -sf ~/.config/kitty/style/$KITTYTHEME.conf ~/.config/kitty/style.conf

# ------------------------------------ XFCE
# xfconf-query -c xsettings -p /Net/ThemeName -s "Adwaita$SWITCHTO"
# xfconf-query -c xsettings -p /Net/IconThemeName -s "Adwaita$SWITCHTO"

# ------------------------------------ HYPRLOCK
ln -sf ~/.config/hypr/hyprlock/hyprlock$SWITCHTO.conf ~/.config/hypr/hyprlock.conf

# ------------------------------------ RESTART WAYBAR
#killall -SIGUSR2 waybar
